proyecto_boneo/apps/aula_virtual/clases/urls.py
# place app url patterns here
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from proyecto_boneo.apps.administracion.usuarios.decorators import user_is_not_alumno, user_is_alumno, user_is_staff, \
    user_is_profesor, user_is_not_profesor

clases_virtuales_patterns = [
   url(r'^$', login_required(views.ClaseVirtualListView.as_view()),
       name='clases_virtuales'),

   url(r'^nuevo/$', user_is_profesor(views.ClaseVirtualCreateView.as_view()),
       name='nueva_clase_virtual'),

   url(r'^ver/(?P<pk>\d+)/$', user_is_profesor(views.ClaseVirtualDetailView.as_view()),
        name='ver_clase_virtual'),

   url(r'^editar/(?P<pk>\d+)/$', user_is_profesor(views.ClaseVirtualUpdateView.as_view()),
       name='editar_clase_virtual'),

   url(r'^eliminar/(?P<pk>\d+)/$', user_is_profesor(views.ClaseVirtualDeleteView.as_view()),
       name='eliminar_clase_virtual'),

   url(r'^ingresar/(?P<pk>\d+)/$', login_required(views.ClaseVirtualIngresarDetailView.as_view()),
        name='ingresar_clase_virtual'),

   url(r'^resolver/(?P<pk>\d+)/$', login_required(views.ClaseVirtualResolverEjercicioView.as_view()),
        name='resolver_ejercicio'),

    url(r'^corregir-resultados/(?P<pk>\d+)/$',
        login_required(views.ClaseVirtualCorreccionListView.as_view()),
        name='corregir_resultados_clase_virtual'),

    url(r'^corregir-resultados/(?P<pk>\d+)/alumno/(?P<alumno_pk>\d+)/$',
        login_required(views.ClaseVirtualCorreccionResultadosView.as_view()),
        name='corregir_resultados_clase_virtual'),

    url(r'^resultados/(?P<pk>\d+)/$', login_required(views.ClaseVirtualResultadosView.as_view()),
        name='resultados_clase_virtual'),

     url(r'^ayuda/clase_virtual$',
       login_required(views.ClaseVirtualAyudaTemplateView.as_view()),
       name='ayuda_clase_virtual'),

    url(r'^ayuda/ver_clase_virtual$',
       login_required(views.ClaseVirtualAyudaVerTemplateView.as_view()),
       name='ayuda_ver_clase_virtual'),

   url(r'^ayuda/nuevo_clase_virtual$',
       login_required(views.ClaseVirtualAyudaNuevoTemplateView.as_view()),
       name='ayuda_nuevo_clase_virtual'),

   url(r'^ayuda/editar_clase_virtual$',
       login_required(views.ClaseVirtualAyudaEditarTemplateView.as_view()),
       name='ayuda_editar_clase_virtual'),

   url(r'^ayuda/eliminar_clase_virtual$',
       login_required(views.ClaseVirtualAyudaEliminarTemplateView.as_view()),
       name='ayuda_eliminar_clase_virtual')
]


ejercicios_patterns = [
   # url(r'^(?P<claseid>\d+)/ejercicio/nuevo/$', user_is_profesor(views.EjercicioVirtualCreateView.as_view()),
   #     name='nuevo_ejercicio'),

   url(r'^(?P<clase_id>\d+)/ejercicio_texto/nuevo/$', user_is_profesor(views.EjercicioVirtualTextoCreateView.as_view()),
       name='nuevo_ejercicio_texto'),

   url(r'^(?P<clase_id>\d+)/ejercicio_multiple_choice/nuevo/$', user_is_profesor(views.EjercicioVirtualMultipleChoiceCreateView.as_view()),
       name='nuevo_ejercicio_multiple_choice'),

   url(r'^ejercicio_texto/editar/(?P<pk>\d+)/$', user_is_profesor(views.EjercicioVirtualTextoUpdateView.as_view()),
       name='editar_ejercicio_texto'),

   url(r'^ejercicio_multiple_choice/editar/(?P<pk>\d+)/$', user_is_profesor(views.EjercicioVirtualMultipleChoiceUpdateView.as_view()),
       name='editar_ejercicio_multiple_choice'),

   url(r'^ejercicio/eliminar/(?P<pk>\d+)/$', user_is_profesor(views.EjercicioVirtualDeleteView.as_view()),
       name='eliminar_ejercicio')

]

urlpatterns = clases_virtuales_patterns + ejercicios_patterns

proyecto_boneo/apps/aula_virtual/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'aula_virtual'

urlpatterns = [
    url(r'^$', login_required(views.AulaVirtualHomeView.as_view()), name='home_administracion'),
    url(r'^biblioteca/', include('proyecto_boneo.apps.aula_virtual.biblioteca.urls')),
    url(r'^clases/', include('proyecto_boneo.apps.aula_virtual.clases.urls')),
    url(r'^comunicados/', include('proyecto_boneo.apps.aula_virtual.comunicados.urls')),
    url(r'^perfil_academico/', include('proyecto_boneo.apps.aula_virtual.perfil_academico.urls'))
]

proyecto_boneo/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from proyecto_boneo.apps.gutils.django.forms.typeahead.views import TypeaheadAddModelView, TypeaheadView

from .views import (home_redirect_router, IndiceView,
                    CalendarioAyudaTemplateView, NuevasClasesVirtualesAyudaTemplateView,
                    ProximosEncuentrosTutoriaAyudaTemplateView)

typeahead_patterns = [
    url(r'^typeahead/$', TypeaheadView.as_view(), name='typeahead'),
    url(r'^typeahead-add/(?P<lookup_name>\w+)$', TypeaheadAddModelView.as_view(),
        name='typeahead-add'),
]

auth_patterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

project_patterns = [
    url(r'^$', login_required(home_redirect_router), name='home'),
    url(r'api/', include('proyecto_boneo.apps.api.urls')),
    url(r'administracion/', include('proyecto_boneo.apps.administracion.urls')),
    url(r'aula_virtual/', include('proyecto_boneo.apps.aula_virtual.urls')),
    url(r'^indice/$', IndiceView.as_view(), name='indice'),
    url(r'^ayuda/proximos_encuentros_tutoria/$', ProximosEncuentrosTutoriaAyudaTemplateView.as_view(),
        name='ayuda_proximos_encuentros_tutoria'),
    url(r'^ayuda/nuevas_clases_virtuales/$', NuevasClasesVirtualesAyudaTemplateView.as_view(),
        name='ayuda_nuevas_clases_virtuales'),
    url(r'^ayuda/calendario/$', CalendarioAyudaTemplateView.as_view(), name='ayuda_calendario')
]

media_patterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = auth_patterns + typeahead_patterns + project_patterns + media_patterns

proyecto_boneo/apps/aula_virtual/clases/models.py
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver

from proyecto_boneo.apps.administracion.planes.models import Materia
from proyecto_boneo.apps.administracion.alumnos.models import Alumno, InscripcionAlumno
from proyecto_boneo.apps.administracion.planes.models import InstanciaCursado
from proyecto_boneo.apps.firebase.models import FireBaseToken


class ClaseVirtual(models.Model):

    class Meta:
        ordering = ('fecha', 'materia', 'tipo')

    EVALUACION = 'eva'
    EVALUACION_ESCRITA = 'esc'
    CLASE_NORMAL = 'nor'

    TIPO_CHOICES = (
        (CLASE_NORMAL, 'Clase Virtual'),
        (EVALUACION, 'Evaluación'),
        (EVALUACION_ESCRITA, 'Evaluación Escrita'),
    )
    fecha = models.DateField()
    materia = models.ForeignKey(Materia, related_name='clases_virtuales', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, default='Clase')
    descripcion = models.CharField(max_length=100)
    tipo = models.CharField(max_length=3, choices=TIPO_CHOICES)

    def __str__(self):
        return '{}: {} de {}'.format(self.nombre, self.descripcion_tipo, self.materia.descripcion)

    @property
    def descripcion_tipo(self):
        return [t[1] for t in self.TIPO_CHOICES if t[0] == self.tipo][0]

    def es_resuelta_alumno(self, alumno):
        return RespuestaEjercicioVirtual.objects.filter(clase_virtual=self).filter(alumno=alumno).count() > 0

    def es_corregida_alumno(self, alumno):
        respuesta_list = RespuestaEjercicioVirtual.objects.filter(clase_virtual=self).filter(alumno=alumno)
        for respuesta in respuesta_list:
            if respuesta.puntaje_obtenido is None:
                return False
        return True

    def obtener_puntaje_alumno(self, alumno):
        return RespuestaEjercicioVirtual.objects.filter(clase_virtual=self).filter(
            alumno=alumno).aggregate(Sum("puntaje_obtenido"))["puntaje_obtenido__sum"]


class EjercicioVirtual(models.Model):
    TEXTO = 'txt'
    MULTIPLE_CHOICE = 'mch'

    TIPO_CHOICES = (
        (TEXTO, 'Texto'),
        (MULTIPLE_CHOICE, 'Multiple Choice'),
    )

    tipo_ejercicio = models.CharField(max_length=3, choices=TIPO_CHOICES)
    clase_virtual = models.ForeignKey(ClaseVirtual, related_name='ejercicios', on_delete=models.CASCADE)
    puntaje = models.FloatField(null=True, blank=True)
    orden_prioridad = models.IntegerField(null=True, blank=True)

    consigna = models.CharField(max_length=100)
    ayuda = models.TextField(null=True, blank=True)
    explicacion = models.TextField(null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.consigna)

    @property
    def descripcion_tipo(self):
        return [t[1] for t in self.TIPO_CHOICES if t[0] == self.tipo_ejercicio][0]


class OpcionEjercicio(models.Model):
    texto = models.CharField(max_length=100)
    ejercicio = models.ForeignKey(EjercicioVirtual, related_name='opciones', on_delete=models.CASCADE)
    opcion_correcta = models.BooleanField(default=False)


class RespuestaEjercicioVirtual(models.Model):
    alumno = models.ForeignKey(Alumno, related_name='respuestas', on_delete=models.CASCADE)
    clase_virtual = models.ForeignKey(ClaseVirtual, related_name='respuestas', on_delete=models.CASCADE)
    ejercicio = models.ForeignKey(EjercicioVirtual, related_name='respuestas', on_delete=models.CASCADE)

    texto = models.TextField(null=True, default=None)
    opcion_seleccionada = models.ForeignKey(OpcionEjercicio, related_name='+', null=True, on_delete=models.CASCADE)
    puntaje_obtenido = models.FloatField(null=True, blank=True)
    observaciones = models.TextField(null=True, default=None, blank=True)


class ResultadoEvaluacion(models.Model):
    clase_virtual = models.ForeignKey(ClaseVirtual, related_name='resultados', on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, related_name='resultados_evaluaciones', on_delete=models.CASCADE)
    nota = models.FloatField()
    fecha_correccion = models.DateTimeField(auto_now=True)
    fecha_notificado = models.DateTimeField(null=True, default=None)


@receiver(post_save, sender=ResultadoEvaluacion)
def send_resultado_evaluacion_firebase_notifications(sender, instance=None, created=False, **kwargs):
    if created:
        inscripcion_alumno = InscripcionAlumno.objects.filter(
            alumno=instance.alumno, instancia_cursado__materia=instance.clase_virtual.materia).first()
        FireBaseToken.send_notification(instance.alumno.usuario, {
            'id': str(instance.id),
            'inscripcion_alumno_id': str(inscripcion_alumno.id),
            'fecha': instance.clase_virtual.fecha.isoformat(),
            'evaluacion': instance.clase_virtual.nombre,
        }, FireBaseToken.NOTIFICATION_TYPE_PERFIL_ACADEMICO)


@receiver(post_save, sender=ClaseVirtual)
def send_clase_virtual_firebase_notifications(sender, instance=None, created=False, **kwargs):
    if created:
        alumnos = Alumno.objects.filter(inscripciones__instancia_cursado__in=InstanciaCursado.objects.año_actual(),
                                        inscripciones__instancia_cursado__materia=instance.materia).distinct()
        for alumno in alumnos:
            FireBaseToken.send_notification(alumno.usuario, {
                'id': str(instance.id),
                'fecha': instance.fecha.isoformat(),
                'nombre': instance.nombre,
                'materia': str(instance.materia),
            }, FireBaseToken.NOTIFICATION_TYPE_CLASE_VIRTUAL)

proyecto_boneo/apps/aula_virtual/clases/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory

from proyecto_boneo.apps.gutils.django.forms import BaseModelForm, BaseFilterForm, BaseForm

from . import models
from proyecto_boneo.apps.aula_virtual.clases.models import EjercicioVirtual,OpcionEjercicio


class ClaseVirtualForm(BaseModelForm):
    def __init__(self, profesor, *args, **kwargs):
        super(ClaseVirtualForm, self).__init__(*args, **kwargs)
        self.fields['materia'].queryset = models.Materia.objects.filter(
            instancias_cursado__profesor_titular=profesor).distinct()

    class Meta:
        model = models.ClaseVirtual
        exclude = []


class EjercicioVirtualTextoForm(BaseModelForm):

    class Meta:
        model = models.EjercicioVirtual
        fields = ['ayuda', 'puntaje', 'consigna']


class EjercicioVirtualMultipleChoiceForm(BaseModelForm):

    class Meta:
        model = models.EjercicioVirtual
        fields = ['ayuda', 'puntaje','consigna', 'explicacion']


class OpcionEjercicioMultipleChoiceForm(BaseModelForm):
    class Meta:
        model = models.OpcionEjercicio
        fields = ['texto','opcion_correcta']

OpcionEjercicioVirtualFormSet = inlineformset_factory(EjercicioVirtual, OpcionEjercicio,
                                                      form=OpcionEjercicioMultipleChoiceForm)
OpcionEjercicioVirtualUpdateFormSet = inlineformset_factory(EjercicioVirtual,
                                                            OpcionEjercicio,
                                                            form=OpcionEjercicioMultipleChoiceForm, extra=0)


class ClaseVirtualFilterForm(BaseFilterForm):
    descripcion = forms.CharField(max_length=100, label='Descripción')

    class Meta:
        filters = {'descripcion': 'descripcion__icontains', }


class TipoEjercicioForm(BaseForm):
    TEXTO = 'texto'
    MULTIPLE_CHOICE = 'multiple_choice'
    TIPO_EJERCICIO_CHOICES = (
        (TEXTO, 'Ejercicio de Texto'),
        (MULTIPLE_CHOICE, 'Ejercicio de Multiple Choice')
    )

    tipo_ejercicio = forms.ChoiceField(
        choices=TIPO_EJERCICIO_CHOICES,
        label="Agregar ejercicio"
    )


class RespuestaEjercicioVirtualTextoForm(BaseModelForm):
    class Meta:
        model = models.RespuestaEjercicioVirtual
        fields = ['texto']


class RespuestaEjercicioVirtualMultipleChoiceForm(BaseModelForm):
    class Meta:
        model = models.RespuestaEjercicioVirtual
        fields = ['opcion_seleccionada']


class RespuestaEjercicioVirtualCorreccionForm(BaseModelForm):
    class Meta:
        model = models.RespuestaEjercicioVirtual
        fields = ['puntaje_obtenido', 'id', 'observaciones']
        labels = {}
        widgets = {'id': forms.HiddenInput()}

CorregirRespuestaEjercicioVirtualFormSet = modelformset_factory(models.RespuestaEjercicioVirtual,
                                                                form=RespuestaEjercicioVirtualCorreccionForm,
                                                                extra=0)


class CorregirEvaluacionEscritaForm(BaseForm):
    nota = forms.FloatField(label='Nota', min_value=1, max_value=10)

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_confirm_delete.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Eliminar clase virtual{% endblock %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <p>¿Desea eliminar la clase virtual "{{ object }}"?</p>
        <button type="submit" class="btn btn-danger">
            <i class="fa fa-trash"></i> Confirmar
        </button>
        <a class="btn btn-default" href="{% url 'aula_virtual:clases_virtuales' %}">
            <i class="fa fa-arrow-circle-left"></i>  Volver
        </a>
    </form>
{% endblock %}

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_corregir_evaluacion_escrita.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Clases virtuales{% endblock %}
{% block content %}
    <script>

    </script>
    <h3>Clase Virtual</h3>
    <p>
        Nombre: {{ clase_virtual.nombre }}
    </p>
    <p>
        Materia: {{ clase_virtual.materia }}
    </p>
    <p>
        Descripción: {{ clase_virtual.descripcion }}
    </p>
    <p>
        Tipo: {{ clase_virtual.descripcion_tipo }}
    </p>
    <form method="post" class="form-horizontal" action="">
        {% csrf_token %}
        <div class="input-group">
            {{ form.nota.label_tag }}
            {{ form.nota }}
            {{ form.nota.errors }}
        </div>
        <div class="clearfix"></div>
        <div class="col-xs-6 col-sm-4">
            <a class="btn btn-default" href="{% url 'aula_virtual:corregir_resultados_clase_virtual' clase_virtual.id %}">
                <i class="fa fa-arrow-circle-left"></i>  Volver
            </a>
        </div>
        <div class="col-xs-6 col-sm-offset-4 col-sm-4">
            <button class="btn btn-success pull-right" type="submit">
                <i class="fa fa-save"></i>  Guardar Correción
            </button>
        </div>
    </form>
{% endblock %}

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_form.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Clase Virtual{% endblock %}
{% block content %}
    <h3 class="inline-title">Clase Virtual</h3> <span class=""><a href="{% url 'aula_virtual:ayuda_nuevo_clase_virtual' %}" onclick="window.open('{% url 'aula_virtual:ayuda_nuevo_clase_virtual' %}', 'newwindow', 'width=600, height=400'); return false;"><i class="fa fa-question-circle"></i></a></span>

    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>
        <div class="form-group">
            {{ form.fecha.label_tag }}
            {{ form.fecha }}
            {{ form.fecha.errors }}
        </div>
        <div class="form-group">
            {{ form.materia.label_tag }}
            {{ form.materia }}
            {{ form.materia.errors }}
        </div>
        <div class="form-group">
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
            {{ form.descripcion.errors }}
        </div>

        <div class="form-group">
            {{ form.tipo.label_tag }}
            {{ form.tipo }}
            {{ form.tipo.errors }}
        </div>

        <button type="submit" class="btn btn-success">
            <i class="fa fa-plus-circle"></i> Guardar
        </button>
        <a class="btn btn-default" href="{% url 'aula_virtual:clases_virtuales' %}">
            <i class="fa fa-arrow-circle-left"></i>  Volver
        </a>
    </form>
{% endblock %}

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_ingresar.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Clases virtuales{% endblock %}
{% block content %}
    <script>

    </script>

    <h3 class="inline-title">Clase Virtual</h3>

        <p>
            Nombre: {{ object.nombre }}
        </p>
        <p>
            Materia: {{ object.materia }}
        </p>
        <p>
            Descripcion:{{ object.descripcion }}
        </p>

    <form action="{% url 'aula_virtual:resolver_ejercicio' object.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-success" type="submit">
            <i class="fa fa-arrow-circle-left"></i>  Comenzar clase virtual
        </button>
    </form>

    <a class="btn btn-default" href="{% url 'aula_virtual:clases_virtuales' %}">
        <i class="fa fa-arrow-circle-left"></i>  Volver
    </a>
{% endblock %}

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_list.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Clases Virtuales{% endblock %}
{% block content %}
    <h3 class="inline-title">Clases Virtuales</h3> <span class=""><a href="{% url 'aula_virtual:ayuda_clase_virtual' %}" onclick="window.open('{% url 'aula_virtual:ayuda_clase_virtual' %}', 'newwindow', 'width=600, height=400'); return false;"><i class="fa fa-question-circle"></i></a></span>
    {% if user.is_profesor %}
        <div class="row">
            <div class="col-xs-12">
                 <a class="btn btn-success" href="{% url 'aula_virtual:nueva_clase_virtual' %}">
                    <i class="fa fa-plus-circle"></i> Nuevo
                 </a>
            </div>
        </div>
    {% endif %}
<div class="row">
    <div class="col-xs-15">
    {% if object_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Materia</th>
                    <th>Tipo</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    {% if activateViewingButtons %}
                        <th></th>
                    {% endif %}
                    {% if activateEditingButtons %}
                        <th></th>
                        <th></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for clase_virtual in object_list %}
                    <tr>
                        <td>{{ clase_virtual.fecha}}</td>
                        <td>{{ clase_virtual.materia }}</td>
                        <td>{{  clase_virtual.descripcion_tipo }}</td>
                        <td>{{ clase_virtual.nombre}}</td>
                        <td>{{ clase_virtual.descripcion }}</td>
                        {% if user.is_profesor %}
                            <td>
                                <a class="btn btn-default" href="{% url 'aula_virtual:corregir_resultados_clase_virtual' clase_virtual.id %}">
                                    <i class="fa fa-pencil"></i> Corregir
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-default" href="{% url 'aula_virtual:editar_clase_virtual' clase_virtual.id %}">
                                    <i class="fa fa-edit"></i> Editar
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-danger" href="{% url 'aula_virtual:eliminar_clase_virtual' clase_virtual.id %}">
                                    <i class="fa fa-trash"></i> Eliminar
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No hay clases virtuales que coincidan con el criterio de filtrado</p>
    {% endif %}
    </div>
</div>
{% endblock %}

proyecto_boneo/apps/aula_virtual/clases/templates/clase_virtual/clase_virtual_view.html
{% extends 'clase_virtual/base.html' %}
{% block title %}Clases virtuales{% endblock %}
{% block content %}
    <script>
        const creationUrls = {
            'texto':'{% url 'aula_virtual:nuevo_ejercicio_texto' object.id %}',
            'multiple_choice':'{% url 'aula_virtual:nuevo_ejercicio_multiple_choice' object.id %}'
        };
        var calculateEjercicioCreationUrl = function(ejercicio_key){
            if(creationUrls.hasOwnProperty(ejercicio_key)){
                return creationUrls[ejercicio_key];
            }
            else{
                return '';
            }
        };

        var setEjercicioCreationButton = function($button,newHref){
            if(newHref){
                $button.attr('href', newHref);
            }
        };

        $(document).ready(function(){
            var $tipoEjercicioSelect = $("#id_tipo_ejercicio");
            var $tipoEjercicioCrearBtn = $("#btn_crear_tipo_ejercicio");

            const defaultTipoKey = $tipoEjercicioSelect.val();

            setEjercicioCreationButton(
                    $tipoEjercicioCrearBtn,
                    calculateEjercicioCreationUrl(defaultTipoKey)
            );

            $tipoEjercicioSelect.on('change', function() {
              var newUrl = calculateEjercicioCreationUrl(this.value);
                if(newUrl != null && newUrl != ''){
                    $tipoEjercicioCrearBtn.attr('disabled', false);
                    setEjercicioCreationButton($tipoEjercicioCrearBtn,newUrl);
                }
                else{
                    $tipoEjercicioCrearBtn.attr('disabled', true);
                }

            });
        });
    </script>

    <h3 class="inline-title">Clase Virtual</h3>
    <p>
        Nombre: {{ object.nombre }}
    </p>
    <p>
        Materia: {{ object.materia }}
    </p>
    <p>
        Descripcion: {{ object.descripcion }}
    </p>
    <p>
        Tipo: {{ object.descripcion_tipo }}
    </p>
    {% if object.tipo != object.EVALUACION_ESCRITA %}
        <div class="row">
            <div class="col-sm-8">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ tipo_ejercicio_form.tipo_ejercicio.label_tag }}
                    <div class="input-group">
                        {{ tipo_ejercicio_form.tipo_ejercicio }}
                        {{ tipo_ejercicio_form.tipo_ejercicio.errors }}
                        <div class="input-group-btn">
                            <a class="btn btn-success" id="btn_crear_tipo_ejercicio" href="#">
                                <i class="fa fa-plus-circle"></i>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <table class="table">
            <thead>
                <th style="width: 15%;">Tipo</th>
                <th style="width: 50%;">Ejercicio</th>
                <th style="width: 5%;">Puntaje</th>
                <th style="width: 15%;"></th>
                <th style="width: 15%;"></th>
            </thead>
            <tbody>
                {% for ejercicio in object.ejercicios.all %}
                    <tr>
                        <td>
                            {%  if ejercicio.tipo_ejercicio == 'mch'  %}
                                Texto
                            {%  endif %}
                            {%  if ejercicio.tipo_ejercicio == 'txt'  %}
                                Multiple Choice
                            {%  endif %}
                        </td>
                        <td>
                            {{ ejercicio }}
                        </td>
                        <td>
                            {{ ejercicio.puntaje }}
                        </td>
                        <td>
                            <a class="btn btn-default btn-block"
                            {% if ejercicio.tipo_ejercicio == "txt" %}
                                   href="{% url 'aula_virtual:editar_ejercicio_texto' ejercicio.id %}">
                            {% elif ejercicio.tipo_ejercicio == "mch" %}
                                   href="{% url 'aula_virtual:editar_ejercicio_multiple_choice' ejercicio.id %}">
                            {% endif %}
                                <i class="fa fa-edit"></i> Editar
                            </a>

                        </td>
                        <td>
                            <a class="btn btn-danger btn-block" href="{% url 'aula_virtual:eliminar_ejercicio' ejercicio.id %}">
                                <i class="fa fa-trash"></i> Eliminar
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <a class="btn btn-default" href="{% url 'aula_virtual:clases_virtuales' %}">
        <i class="fa fa-arrow-circle-left"></i>  Volver
    </a>
{% endblock %}