proyecto_boneo/apps/administracion/estadias/urls.py
# place app url patterns here
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from proyecto_boneo.apps.administracion.usuarios.decorators import user_is_staff

app_name = 'estadias'

urlpatterns = [
   url(r'^$', user_is_staff(views.EstadiasListView.as_view()),
       name='estadias'),

   url(r'^nuevo/$', user_is_staff(views.EstadiaCreateView.as_view()),
       name='nuevo_estadia'),

  url(r'^ver/(?P<pk>\d+)/$', user_is_staff(views.EstadiaDetailView.as_view()),
       name='ver_estadia'),

   url(r'^editar/(?P<pk>\d+)/$', user_is_staff(views.EstadiaUpdateView.as_view()),
       name='editar_estadia'),

   url(r'^eliminar/(?P<pk>\d+)/$', user_is_staff(views.EstadiaDeleteView.as_view()),
       name='eliminar_estadia'),

   url(r'^ayuda/estadia$',
       login_required(views.EstadiaAyudaTemplateView.as_view()),
       name='ayuda_estadias'),

   url(r'^ayuda/nuevo_estadia$',
       login_required(views.EstadiaAyudaNuevoTemplateView.as_view()),
       name='ayuda_nuevo_estadia'),

   url(r'^ayuda/editar_estadia$',
       login_required(views.EstadiaAyudaEditarTemplateView.as_view()),
       name='ayuda_editar_estadia'),

   url(r'^ayuda/eliminar_estadia$',
       login_required(views.EstadiaAyudaEliminarTemplateView.as_view()),
       name='ayuda_eliminar_estadia'),

]

proyecto_boneo/apps/administracion/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'administracion'

urlpatterns = [
    url(r'^$', login_required(views.AdministracionHomeView.as_view()), name='home'),
    url(r'^alumnos/', include('proyecto_boneo.apps.administracion.alumnos.urls')),
    url(r'^personal/', include('proyecto_boneo.apps.administracion.personal.urls')),
    url(r'^planes/', include('proyecto_boneo.apps.administracion.planes.urls')),
    url(r'^tutorias/', include('proyecto_boneo.apps.administracion.tutorias.urls')),
    url(r'^estadias/', include('proyecto_boneo.apps.administracion.estadias.urls')),
    url(r'^usuarios/', include('proyecto_boneo.apps.administracion.usuarios.urls')),
    url(r'^eventos/', include('proyecto_boneo.apps.administracion.eventos.urls')),
]

proyecto_boneo/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from proyecto_boneo.apps.gutils.django.forms.typeahead.views import TypeaheadAddModelView, TypeaheadView

from .views import (home_redirect_router, IndiceView,
                    CalendarioAyudaTemplateView, NuevasClasesVirtualesAyudaTemplateView,
                    ProximosEncuentrosTutoriaAyudaTemplateView)

typeahead_patterns = [
    url(r'^typeahead/$', TypeaheadView.as_view(), name='typeahead'),
    url(r'^typeahead-add/(?P<lookup_name>\w+)$', TypeaheadAddModelView.as_view(),
        name='typeahead-add'),
]

auth_patterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

project_patterns = [
    url(r'^$', login_required(home_redirect_router), name='home'),
    url(r'api/', include('proyecto_boneo.apps.api.urls')),
    url(r'administracion/', include('proyecto_boneo.apps.administracion.urls')),
    url(r'aula_virtual/', include('proyecto_boneo.apps.aula_virtual.urls')),
    url(r'^indice/$', IndiceView.as_view(), name='indice'),
    url(r'^ayuda/proximos_encuentros_tutoria/$', ProximosEncuentrosTutoriaAyudaTemplateView.as_view(),
        name='ayuda_proximos_encuentros_tutoria'),
    url(r'^ayuda/nuevas_clases_virtuales/$', NuevasClasesVirtualesAyudaTemplateView.as_view(),
        name='ayuda_nuevas_clases_virtuales'),
    url(r'^ayuda/calendario/$', CalendarioAyudaTemplateView.as_view(), name='ayuda_calendario')
]

media_patterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = auth_patterns + typeahead_patterns + project_patterns + media_patterns

proyecto_boneo/apps/administracion/estadias/models.py
from django.db import models

# Create your models here.
from proyecto_boneo.apps.administracion.alumnos.models import Alumno, Responsable


class Estadia(models.Model):
    responsable = models.ForeignKey(Responsable, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

    def __str__(self):
        return '{} - {}'.format(self.responsable, self.alumno)

proyecto_boneo/apps/administracion/estadias/forms.py
from . import models

# place form definition here
from proyecto_boneo.apps.gutils.django.forms import BaseModelForm
from proyecto_boneo.apps.gutils.django.forms.typeahead.widgets import TypeaheadDropDownModelWidget
from proyecto_boneo.apps.administracion.alumnos.lookups import AlumnoLookup
from proyecto_boneo.apps.administracion.alumnos.lookups import ResponsableSearchLookup


class EstadiaForm(BaseModelForm):

    class Meta:
        model = models.Estadia
        exclude = []
        labels = {}
        widgets = {
            'responsable': TypeaheadDropDownModelWidget(ResponsableSearchLookup),
            'alumno': TypeaheadDropDownModelWidget(AlumnoLookup)
        }

proyecto_boneo/apps/administracion/estadias/views.py
from . import forms, models

from django.urls import reverse_lazy
from proyecto_boneo.apps.gutils.django.views import ListView, CreateView, DetailView, UpdateView, ProtectedDeleteView, TemplateView


class EstadiasListView(ListView):
    model = models.Estadia
    template_name = 'estadias/estadias_list.html'


class EstadiasResponsableListView(ListView):
    model = models.Estadia
    template_name = 'estadias/estadias_list.html'

    def get_queryset(self):
        return models.Estadia.objects.filter(usuario=self.request.user)


class EstadiaDetailView(DetailView):
    model = models.Estadia
    template_name = 'estadias/estadias_view.html'

class EstadiaCreateView(CreateView):
    model = models.Estadia
    success_url = reverse_lazy('administracion:estadias:estadias')
    form_class = forms.EstadiaForm
    template_name = 'estadias/estadias_form.html'


class EstadiaUpdateView(UpdateView):
    model = models.Estadia
    success_url = reverse_lazy('administracion:estadias:estadias')
    form_class = forms.EstadiaForm
    template_name = 'estadias/estadias_form.html'


class EstadiaDeleteView(ProtectedDeleteView):
    model = models.Estadia
    success_url = reverse_lazy('administracion:estadias:estadias')
    template_name = 'estadias/estadias_confirm_delete.html'


class EstadiaAyudaTemplateView(TemplateView):
    template_name = 'estadias/estadias_ayuda_list.html'

class EstadiaAyudaNuevoTemplateView(TemplateView):
    template_name = 'estadias/estadias_ayuda_nuevo.html'

class EstadiaAyudaEditarTemplateView(TemplateView):
    template_name = 'estadias/estadias_ayuda_editar.html'

class EstadiaAyudaEliminarTemplateView(TemplateView):
    template_name = 'estadias/estadias_ayuda_eliminar.html'

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_ayuda_editar.html
{% extends 'ayuda/base.html' %}
{% block title %}Editar estadías{% endblock %}
{% block content %}
<h4>Edicion de estadías</h4>
<p>Se tienen las mismas consideraciones en los campos, que lo expresado para el formulario de creación. Una vez completado los valores del formulario debe hacer clic en el botón confirmar para  que los cambios a los datos de la estadía sean efectivos en el sistema.</p>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_ayuda_eliminar.html
{% extends 'ayuda/base.html' %}
{% block title %}Eliminar estadía{% endblock %}
{% block content %}
<h4>Eliminado de estadías</h4>
<p>Si confirma la eliminación, se verificará que el estadía no esté afectada por operaciones en el sistema, y si es así el sistema procederá a eliminarla definitivamente del sistema. En el caso que esté relacionado a operaciones existentes, indicará la situación y cancelará el proceso de eliminación.</p>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_ayuda_list.html
{% extends 'ayuda/base.html' %}
{% block title %}Listado estadía{% endblock %}
{% block content %}
<h4>Listado de estadías</h4>
<p>Al ingresar al módulo de estadías, se presenta un listado con los estadías del sistema, y filtros por campo para facilitar la búsqueda de las estadías.</p>
    <p>Desde esta pantalla se puede acceder a la pantalla de creación de nuevo estadía, haciendo clic en el botón de nuevo estadía, así como ir a las pantallas de edición o eliminación de una estadía determinado mediante los botones correspondientes presentes en el listado.</p>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_ayuda_nuevo.html
{% extends 'ayuda/base.html' %}
{% block title %}Crear estadías{% endblock %}
{% block content %}
<h4>Creacion de estadías</h4>
<p>
Al seleccionar la opción de crear estadías, se presentará el siguiente formulario:El formulario debe ser llenado con los valores correspondientes, teniendo en cuenta las siguientes consideraciones:
-Para ingresar el profesor debe comenzar a ingresar su nombre, donde inmediatamente se sugerirán las coincidencias y usted podrá seguir completando el nombre por teclado o seleccionarlo de la lista desplegada.
-Para ingresar el alumno debe comenzar a ingresar su nombre, donde inmediatamente se sugerirán las coincidencias y usted podrá seguir completando el nombre por teclado o seleccionarlo de la lista desplegada.
Una vez completado los valores del formulario debe hacer clic en el botón confirmar para que la nueva estadía sea generada en el sistema.
</p>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_confirm_delete.html
{% extends 'administracion/base.html' %}
{% block title %}Eliminar estadias{% endblock %}
{% block content %}
    <h3 class="inline-title">Eliminar estadias</h3> <span class=""><a href="{% url 'administracion:ayuda_eliminar_estadia' %}" onclick="window.open('{% url 'administracion:ayuda_eliminar_estadia' %}', 'newwindow', 'width=600, height=400'); return false;"><i class="fa fa-question-circle"></i></a></span>
    <form method="post" action="">
        {% csrf_token %}
        <p>¿Desea eliminar la estadia "{{ object }}"?</p>
        <button type="submit" class="btn btn-danger">
            <i class="fa fa-trash"></i> Confirmar
        </button>
        <a class="btn btn-default" href="{% url 'administracion:estadias' %}">
            <i class="fa fa-arrow-circle-left"></i>  Volver
        </a>
    </form>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_form.html
{% extends 'administracion/base.html' %}
{% block title %}Estadia{% endblock %}
{% block content %}
    <h3 class="inline-title">Estadía</h3> <span class=""><a href="{% url 'administracion:estadias:ayuda_nuevo_estadia' %}" onclick="window.open('{% url 'administracion:estadias:ayuda_nuevo_estadia' %}', 'newwindow', 'width=600, height=400'); return false;"><i class="fa fa-question-circle"></i></a></span>

    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.responsable.label_tag }}
            {{ form.responsable }}
            {{ form.responsable.errors }}
        </div>
        <div class="form-group">
            {{ form.alumno.label_tag }}
            {{ form.alumno }}
            {{ form.alumno.errors }}
        </div>
        <div class="form-group">
            {{ form.fecha_inicio.label_tag }}
            {{ form.fecha_inicio }}
            {{ form.fecha_inicio.errors }}
        </div>
        <div class="form-group">
            {{ form.fecha_fin.label_tag }}
            {{ form.fecha_fin }}
            {{ form.fecha_fin.errors }}
        </div>

        <button type="submit" class="btn btn-success">
            <i class="fa fa-check-circle"></i> Confirmar
        </button>
        <a class="btn btn-default" href="{% url 'administracion:estadias:estadias' %}">
            <i class="fa fa-arrow-circle-left"></i>  Volver
        </a>
    </form>
{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_list.html
{% extends 'administracion/base.html' %}
{% block title %}Estadías{% endblock %}
{% block content %}
    <div class="col-md-offset-1 col-md-10">
    <h3 class="inline-title">Estadías</h3> <span class=""><a href="{% url 'administracion:estadias:ayuda_estadias' %}" onclick="window.open('{% url 'administracion:estadias:ayuda_estadias' %}', 'newwindow', 'width=600, height=400'); return false;"><i class="fa fa-question-circle"></i></a></span>
    <div>
         <a class="btn btn-success" href="{% url 'administracion:estadias:nuevo_estadia' %}">
            <i class="fa fa-plus-circle"></i> Nuevo
         </a>
    </div>

    {% if object_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Responsable</th>
                    <th>Alumno</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    {% if activateViewingButtons %}
                        <th></th>
                    {% endif %}
                    {% if activateEditingButtons %}
                        <th></th>
                        <th></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for estadia in object_list %}
                    <tr>
                        <td>{{ estadia.responsable}}</td>
                        <td>{{ estadia.alumno }}</td>
{#                        <td>#}
{#                            {% for destinatario in estadia.destinatarios.all %} {{ destinatario }}<br/>{% endfor %}#}
{#                        </td>#}
                        <td>{{ estadia.fecha_inicio }}</td>
                        <td>{{ estadia.fecha_fin }}</td>
                        {% if user.is_profesor %}
                            <td>
                                <a class="btn btn-default" href="{% url 'administracion:estadias:ver_estadia' estadia.id %}">
                                    <i class="fa fa-eye"></i> Ver
                                </a>
                            </td>
                        {% endif %}
                        {% if user.is_staff %}
                            <td>
                                <a class="btn btn-primary" href="{% url 'administracion:estadias:editar_estadia' estadia.id %}">
                                    <i class="fa fa-edit"></i> Editar
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-danger" href="{% url 'administracion:estadias:eliminar_estadia' estadia.id %}">
                                    <i class="fa fa-trash"></i> Eliminar
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No hay estadías que coincidan con el criterio de filtrado</p>
    {% endif %}
    </div>

{% endblock %}

proyecto_boneo/apps/administracion/estadias/templates/estadias/estadias_view.html
{% extends 'administracion/base.html' %}
{% block title %}Estadia{% endblock %}
{% block content %}

    <h3>Estadia</h3>

        <p>
            Responsable: {{ object.responsable }}
        </p>
        <p>
            Alumno: {{ object.alumno }}
        </p>
        <p>
            Fecha inicio:{{ object.fecha_inicio }}
        </p>
        <p>
            Fecha fin:{{ object.fecha_fin }}
        </p>


        <a class="btn btn-default" href="{% url 'administracion:estadias' %}">
            <i class="fa fa-arrow-circle-left"></i>  Volver
        </a>
{% endblock %}